// chatbot-frontend/src/components/ConversationsList.jsx
const ConversationsList = ({ sessions, currentSession, onSessionChange }) => {
    return (
        <div className="w-64 border-r p-4 hidden md:block">
            <h2 className="text-lg font-semibold mb-4">Conversations</h2>
            <div className="space-y-2">
                {sessions.map((session) => (
                    <button
                        key={session}
                        onClick={() => onSessionChange(session)}
                        className={`w-full text-left px-3 py-2 rounded-lg ${currentSession === session
                                ? 'bg-blue-100 text-blue-800'
                                : 'hover:bg-gray-100'
                            }`}
                    >
                        Session {session.slice(-6)}
                    </button>
                ))}
            </div>
        </div>
    );
};
export default ConversationsList;

// finance-chatbot-front/src/app/components/conversations-list/conversations-list.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-conversations-list',
  templateUrl: './conversations-list.component.html',
  styleUrls: ['./conversations-list.component.css'],
})
export class ConversationsListComponent {
  @Input() sessions: string[] = []; // Liste des sessions
  @Input() currentSession: string = ''; // Session actuelle
  @Output() sessionChange = new EventEmitter<string>();

  isSidebarOpen = false; // État de la sidebar

  /**
   * Méthode pour basculer l'état de la sidebar.
   */
  toggleSidebar() {
    this.isSidebarOpen = !this.isSidebarOpen;
  }

  /**
   * Méthode pour gérer le changement de session.
   * @param session - La session sélectionnée
   */
  changeSession(session: string) {
    this.sessionChange.emit(session);
  }
}

<!-- Bouton pour basculer la sidebar -->
<button
  (click)="toggleSidebar()"
  class="toggle-sidebar-btn px-4 py-2 bg-blue-500 text-white rounded-lg mb-4"
>
  {{ isSidebarOpen ? 'Fermer' : 'Ouvrir' }} Conversations
</button>

<!-- Sidebar -->
<div
  class="sidebar w-64 border-r p-4"
  [ngClass]="{ 'hidden': !isSidebarOpen, 'block': isSidebarOpen }"
>
  <h2 class="text-lg font-semibold mb-4">Conversations</h2>
  <div class="space-y-2">
    <button
      *ngFor="let session of sessions"
      (click)="changeSession(session)"
      class="w-full text-left px-3 py-2 rounded-lg"
      [ngClass]="{
        'bg-blue-100 text-blue-800': currentSession === session,
        'hover:bg-gray-100': currentSession !== session
      }"
    >
      Session {{ session.slice(-6) }}
    </button>
  </div>
</div>
